version: '3'
services:
  mysql:
    container_name: mysql
    image: mysql:5.7.20
    volumes:
      - bd-data:/var/lib/mysql
    environment:
      - "MYSQL_DATABASE=etax"
      - "MYSQL_USER=root"
      - "MYSQL_PASSWORD=root"
      - "MYSQL_ROOT_PASSWORD=root"
    ports:
      - "3306:3306"
    networks:
      - default-net
    tty: false
  php:
    container_name: php
    build:
      context: ./docker/php
    volumes:
      - ./:/var/www
      - ./docker/php/custom.ini:/usr/local/etc/php/conf.d/custom.ini
      - ./docker/php/cacert.pem:/usr/local/etc/php/conf.d/cacert.pem
    tty: false
    networks:
      - default-net
  nginx:
    container_name: nginx
    image: nginx:1.12.2
    working_dir: /var/www
    volumes:
       - ./:/var/www
       - ./docker/nginx/vhost.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:80
    networks:
       - default-net
    tty: false
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    environment:
       - 'PMA_HOST=mysql'
    ports:
      - "8081:80"
    networks:
      - default-net
    depends_on:
      - mysql
    tty: false
  redis:
    container_name: redis
    image: redis:latest
    volumes:
      - redis-data:/data
    networks:
      - default-net
    tty: false
networks:
  default-net:
volumes:
  bd-data:
  redis-data:

