#!/bin/bash

# Beginning
echo "";
echo "########################################"
echo "#      eTax App                  #"
echo "########################################"
echo ""
echo "              _______                   "
echo "             //  ||\ \                  "
echo "       _____//___||_\ \___              "
echo "       )  _          _    \             "
echo "       |_/ \________/ \___|             "
echo "      ___\_/________\_/______           "
echo ""

composer install
php artisan config:clear
php artisan config:clear
php artisan route:clear
php artisan view:clear
php artisan migrate:fresh
php artisan key:generate
php artisan db:seed


