#!/bin/bash

# Beginning 
echo "";
echo "########################################"
echo "#      eTax App                  #"
echo "########################################"
echo ""
echo "              _______                   "
echo "             //  ||\ \                  "
echo "       _____//___||_\ \___              "
echo "       )  _          _    \             "
echo "       |_/ \________/ \___|             "
echo "      ___\_/________\_/______           "
echo ""

docker-compose down --remove-orphans
docker-compose up --build -d redis mysql php nginx phpmyadmin
docker exec php composer update
docker exec php php artisan config:clear
docker exec php php artisan config:clear
docker exec php php artisan route:clear
docker exec php php artisan view:clear
docker exec php php artisan migrate
docker exec php php artisan db:seed